"use client"

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LE4p9Ez46RM
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import Link from "next/link"

const Login= () =>  {
  return (
    <div key="1" className="w-full h-screen flex items-center justify-center bg-gray-100 dark:bg-gray-800">
      <div className="w-full max-w-md p-6 space-y-6">
        <div className="flex items-center justify-center">
          <h1 className="text-2xl font-bold">Login</h1>
        </div>
        <div className="space-y-4" id="login-form">
          <div className="space-y-2">
            <Label htmlFor="email">Email</Label>
            <Input id="email" placeholder="m@example.com" required type="email" />
            <Label htmlFor="password">Password</Label>
            <Input id="password" required type="password" />
          </div>
          <Button className="w-full" type="submit">
            Login
          </Button>
          {/* <div className="flex justify-center">
            <Link className="text-sm text-blue-500 hover:underline" href="#">
              Forgot Password?
            </Link>
          </div> */}
        </div>
      </div>
    </div>
  )
}
export default Login;